---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Execute
      ansible.builtin.include_role:
        name: mamono210.molecule_ec2_driver
      vars:
        molecule_ec2_driver_resource_state: 'present'
