---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ghcr.io/docker-hub-tm/ansible-test/${MOLECULE_DISTRO:-centos7}:latest
    pre_build_image: true
    aws_access_key_id: ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    aws_region: ${AWS_REGION}
    local_file_name: ${TIMESTAMP}.txt
    s3_bucket: ${AWS_S3_BUCKET}
    s3_object_name: /molecule-test/${TIMESTAMP}
    test_string: "${TIMESTAMP}"
    upload_file_path: /tmp/${TIMESTAMP}.txt
    working_dir: /tmp/s3
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: ansible.posix.profile_tasks
  connection_options:
    aws_access_key_id: ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    aws_region: ${AWS_REGION}
    local_file_name: ${TIMESTAMP}.txt
    pip_executable: pip
    pip_package: python-pip
    s3_bucket: ${AWS_S3_BUCKET}
    s3_object_name: /molecule-test/${TIMESTAMP}
    upload_file_path: ${TIMESTAMP}.txt
    remote_directory: '{{ working_dir }}'
    remote_file_name: '{{ local_file_name }}'
    working_dir: /tmp/s3
  log: true
  playbooks:
    converge: ../../get.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
