---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE}
    pre_build_image: true
    aws_region: ${AWS_REGION}
    local_file_group: circleci
    local_file_name: ${TIMESTAMP}.txt
    local_file_owner: circleci
    s3_bucket: ${AWS_S3_BUCKET}
    s3_object_name: /ansible-playbooks-mamono210/aws-s3/get/${TIMESTAMP}
    test_string: ${TIMESTAMP}
    upload_file_path: "{{ working_dir }}/{{ local_file_name }}"
    working_dir: '/home/circleci/test_file'
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  connection_options:
    local_file_name: ${TIMESTAMP}.txt
    s3_bucket: ${AWS_S3_BUCKET}
    s3_object_name: /ansible-playbooks-mamono210/aws-s3/get/${TIMESTAMP}
    upload_file_path: "{{ working_dir }}/{{ local_file_name }}"
    remote_directory: '{{ working_dir }}'
    remote_file_name: '{{ local_file_name }}'
    working_dir: '/home/circleci/test_file'
  log: true
  playbooks:
    converge: ../../get.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
