---
- name: Prepare
  hosts: localhost

  tasks:
    - name: Create directory for creating test text file
      ansible.builtin.file:
        path: '{{ item.working_dir }}'
        state: directory
        mode: '0777'
        owner: '{{ item.local_file_owner }}'
        group: '{{ item.local_file_group }}'
      delegate_to: localhost
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index

    - name: Create test text file
      ansible.builtin.template:
        src: source.template
        dest: "{{ item.working_dir }}/{{ item.local_file_name }}"
        mode: '0777'
        owner: '{{ item.local_file_owner }}'
        group: '{{ item.local_file_group }}'
      delegate_to: localhost
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index

    - name: Simple PUT operation
      amazon.aws.s3_object:
        bucket: '{{ item.s3_bucket }}'
        object: '{{ item.s3_object_name }}'
        src: "{{ item.working_dir }}/{{ item.local_file_name }}"
        mode: put
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
