---
- hosts: all
  become: true

  roles:
    - role: geerlingguy.repo-epel
      become: True

    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: pip
          - name: boto3
        pip_executable: pip3
        pip_package: python3-pip
        working_dir: /tmp/s3
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "8"

    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: pip
            version: "20.3.4"
          - name: boto3
        pip_executable: pip
        pip_package: python-pip
        working_dir: /tmp/s3
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "7"

  tasks:
    - name: Simple PUT operation
      aws_s3:
        aws_access_key: '{{ aws_access_key_id }}'
        aws_secret_key: '{{ aws_secret_access_key }}'
        region: '{{ aws_region }}'
        bucket: '{{ s3_bucket }}'
        object: '{{ s3_object_name }}'
        src: '{{ upload_file_path }}'
        mode: put
