---
- name: Copy a single file from local to AWS S3
  hosts: all
  become: true

  tasks:
    - name: Run aws_bootstrap (unless skipped)
      ansible.builtin.include_role:
        name: mamono210.aws_bootstrap
      when: not (skip_bootstrap | default(false) | bool)

    - name: Run aws_s3_cp_
      ansible.builtin.include_role:
        name: mamono210.aws_s3_cp
