---
version: 2.1

executors:
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small

orbs:
  ansible-lint: orbss/ansible-lint@0.0.3
  aws-cli: circleci/aws-cli@3.1.1
  molecule-ec2: orbss/molecule-ec2@0.0.9
  yamllint: orbss/yamllint@0.0.4

jobs:
  ansible-lint:
    executor: ansible-lint/default
    steps:
      - checkout
      - ansible-lint/execute:
          molecule-playbook-test: true
  molecule:
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: medium
    parameters:
      ansible-user:
        type: string
      aws-ami-id:
        type: string
      aws-instance-type:
        type: string
      aws-resource-name:
        type: string
      aws-session-duration:
        type: string
      aws-vpc-subnet-id:
        type: string
      circleci-timeout:
        type: string
      molecule-scenario-name:
        type: string
        default: default
    steps:
      - checkout
      - aws-cli/setup
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: << parameters.aws-resource-name >>
          session-duration: << parameters.aws-session-duration >>
      - run:
          name: Install Molecule and dependencies
          command: |
            pip3 install -r molecule/requirements.txt
      - run:
          name: Install required Ansible roles
          command: |
            ansible-galaxy install -r molecule/<< parameters.molecule-scenario-name >>/requirements.yml
      - run:
          name: Configure Molecule config file
          command: |
            NEW_TIMESTAMP_VALUE=$(date "+%s")
            sed -i "s/\${UNIX_TIMESTAMP}/${NEW_TIMESTAMP_VALUE}/g" molecule/<< parameters.molecule-scenario-name >>/molecule.yml
      - molecule-ec2/execute:
          ansible-user: << parameters.ansible-user >>
          aws-ami-id: << parameters.aws-ami-id >>
          aws-instance-type: << parameters.aws-instance-type >>
          aws-resource-name: << parameters.aws-resource-name >>
          aws-vpc-subnet-id: << parameters.aws-vpc-subnet-id >>
          circleci-timeout: << parameters.circleci-timeout >>
          molecule-scenario-name: << parameters.molecule-scenario-name >>
  yamllint:
    executor: yamllint/default
    steps:
      - checkout
      - yamllint/execute
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule:
          ansible-user: 'ec2-user'
          aws-ami-id: 'ami-0a0aa54caf414e700'
          aws-instance-type: 't2.medium'
          aws-resource-name: 'circleci_ansible-playbook_aws_s3_cs9'
          aws-session-duration: '3600'
          aws-vpc-subnet-id: 'subnet-022a704b3061b8b39'
          circleci-timeout: '30m'
          molecule-scenario-name: 's3get'
          context: AWS_OPENID_CONNECT_TOKENS
          requires:
            - ansible-lint
      - molecule:
          ansible-user: 'ec2-user'
          aws-ami-id: 'ami-0a0aa54caf414e700'
          aws-instance-type: 't2.medium'
          aws-resource-name: 'circleci_ansible-playbook_aws_s3_cs9'
          aws-session-duration: '3600'
          aws-vpc-subnet-id: 'subnet-022a704b3061b8b39'
          circleci-timeout: '30m'
          molecule-scenario-name: 's3put'
          context: AWS_OPENID_CONNECT_TOKENS
          requires:
            - ansible-lint
