---
- name: Prepare
  become: true
  hosts: all

  roles:
    - role: mamono210.epel
    - role: mamono210.aws_bootstrap

  tasks:
    - name: Create directory for creating test text file
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/test_file"
        state: directory
        mode: '0777'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'

    - name: Create test text file
      ansible.builtin.template:
        src: source.template
        dest: "/home/{{ ansible_user }}/test_file/{{ item.local_file_name }}"
        mode: '0777'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
