---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    uses: github-actions-reusable-workflows/ansible-lint/.github/workflows/workflows.yml@main

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Yelp detect-secrets
        run: |
          pip install detect-secrets

      - name: Execulte detect-secrets(disabled KeywordDetector plugin)
        run: |
          detect-secrets scan --disable-plugin KeywordDetector \
          | jq .results > results.json

      - name: Check whether detect-secrets found vulnerability
        run: |
          line=$(cat results.json | wc -w)
          if [ $line -gt 2 ]; then
            echo "vulnerability was found"
            detect-secrets scan | jq .results -C
            exit 1;
          fi

      - name: Show detect-secrets version
        run: |
          pip list | grep detect-secrets \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'detect-secrets.* '
          detect-secrets --version

  molecule-s3get:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos7
        python-version:
          - 3.9
        scenario:
          - s3get

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python3 -m pip install -r molecule/requirements.txt

      - name: Create galaxy dependencies file in 'molecule/default/'
        run: cp roles/requirements.yml molecule/${{ matrix.scenario }}/requirements.yml

      - name: Set environment variable with timestamp for making sure Molecule would create unique AWS resources
        run: |
          TIMESTAMP=$(date "+%s")
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Test with molecule
        run: |
          molecule test --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          MOLECULE_DISTRO: ${{ matrix.distro }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          PY_COLORS: '1'
          # TIMESTAMP: sotred in system environment variables

      - name: Show Ansible version
        run: |
          pip list | grep ansible \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
          ansible --version

      - name: Show molecule version
        run: |
          molecule --version
        env:
          PY_COLORS: '1'

  molecule-s3put:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos7
          - centos-stream8
        python-version:
          - 3.9
        scenario:
          - s3put

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python3 -m pip install -r molecule/requirements.txt

      - name: Create galaxy dependencies file in 'molecule/default/'
        run: cp roles/requirements.yml molecule/${{ matrix.scenario }}/requirements.yml

      - name: Create test file
        run: |
          TIMESTAMP=$(date "+%s")
          echo ${TIMESTAMP} > /tmp/${TIMESTAMP}.txt
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Test with molecule
        run: |
          molecule test --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          MOLECULE_DISTRO: ${{ matrix.distro }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          PY_COLORS: '1'
          # TIMESTAMP: sotred in system environment variables

      - name: Show Ansible version
        run: |
          pip list | grep ansible \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
          ansible --version

      - name: Show molecule version
        run: |
          molecule --version
        env:
          PY_COLORS: '1'

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@56310d70ae8fd21afec8d4307d2d9ab6c15e7c5d

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: |
          yamllint --version \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
